# Generated by Django 4.0.5 on 2022-07-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_text_book_book_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_book',
            name='Issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text_book',
            name='Returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
