# Generated by Django 4.0.5 on 2022-07-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='content_type',
        ),
        migrations.AddField(
            model_name='history',
            name='book',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
