# Generated by Django 4.0.5 on 2022-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0003_rename_user_history_student_remove_history_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
