# Generated by Django 4.0.5 on 2022-07-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_siteusers_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUsers',
        ),
    ]
